---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the size according to your needs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app.kubernetes.io/part-of: MilvusDB
    app.openshift.io/runtime: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio-container
          image: quay.io/minio/minio:RELEASE.2023-04-13T03-08-07Z
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          command:
            - "minio"
            - "server"
            - "/data"
            - "--console-address"
            - ":9001"
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-console
spec:
  to:
    kind: Service
    name: minio-service
  port:
    targetPort: 9001
  tls:
    termination: edge
